<?php
/**
 * Soluvas
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 *
 * @category   Soluvas
 * @package    Soluvas_TranslationExporter
 * @copyright  Copyright (c) 2010 Soluvas (http://www.soluvas.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-compilation">Translation Exporter</h3></td>
            <td class="form-buttons">
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
	<p>Translations will be exported to:</p>
	<p><tt>var/translations/(locale)/*.csv</tt></p>
	<form name="export_form" id="export_form" method="post" action="<?php echo Mage::getModel('adminhtml/url')->getUrl('translationexporter/index/export'); ?>">
		<?php echo $this->getBlockHtml('formkey')?>
		<div class="form-buttons">
		<button class="scalable" type="submit"><span>Export Now</span></button>
		</div>
	</form>
</div>
