<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List

 */
?>
<?php 

$_productCollection = $this->getLoadedProductCollection();

?>
<?php 
if($_productCollection->count()): ?>
	<script type="text/javascript">
		jQuery(window).bind("load", function() {
			jQuery("div#slider1").codaSlider()
		});
	</script>
<div class="slider-wrap">
	<div id="slider1" class="csw">
		<div class="panelContainer">
		
<?php  $_iterator = 0; ?>
<?php foreach($_productCollection as $_item): ?>
<?php $_iterator++; ?>
			<div class="panel" title=" <?php echo $_iterator; ?> ">
				<div class="wrapper">
							<div class = "slider-left">
							   <?php echo $_item->getDescription() ?>
							</div>
							<div class = "slider-right">
		                        <?php echo $this->getPriceHtml($_item, true) ?>
			                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(420,250) ?>"  height="250"  width="420" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
		                        <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-info"><?php echo $this->__('Details')?></a>
							</div>
							<div class = "sp"></div>
				</div>
			</div>
<?php endforeach; ?>
		</div><!-- .panelContainer -->
	</div><!-- #slider1 -->
</div><!-- .slider-wrap --> 
<?php endif; ?>   
