<?php
/* @var $this Magneto_Debug_Block_Blocks */

$templateDirs = $this->getTemplateDirs();
$blocks = $this->getItems();
$layoutBlocks = $this->getLayoutBlocks();
$designFilePath = realpath(Mage::getBaseDir('design')) . DS;
?>

<h4><?php echo $this->__('Template path') ?></h4>
<?php if ($templateDirs): ?>
    <ol>
        <?php foreach ($templateDirs as $template): ?>
            <li><?php echo $template; ?></li>
        </ol>
    <?php endforeach; ?>
<?php else: ?>
    <p>None</p>
<?php endif; ?>


<h4><?php echo $this->__('Rendered Blocks') ?></h4>
<p>List of all rendered blocks.</p>
<table>
    <thead>
        <tr>
            <th>#</th>
            <th><?php echo $this->__('name in layout') ?></th>
            <th><?php echo $this->__('block class') ?></th>
            <th><?php echo $this->__('template') ?></th>
            <th><?php echo $this->__('rendering in') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $row = 0; ?>
        <?php foreach ($blocks as $block): ?>
            <tr class="<?php echo ( ($row % 2 ? 'djdebugodd' : 'djdebugeven')) ?>">
                <td><?php echo $row ?></td>
                <td><span style="color:grey;"><?php echo str_repeat("|&nbsp-&nbsp-&nbsp", $block['level']) ?></span><?php echo $block['layout_name'] ?></td>
                <td>
                    <a href="<?php echo $this->getViewBlockUrl($block['class']) ?>"
                       class="remoteCall"><?php echo $block['class'] ?></a>
                    <br /><input type="text" value="<?php
                    echo Mage::helper('debug')->getBlockFilename($block['class']);
                    ?>" size="40" onclick="this.select();" />
                </td>
                <td>
                    <?php
                    if ($block['template']) {
                        ?> 
                        <a href="<?php echo $this->getViewTemplateUrl($block['template']) ?>"
                           class="remoteCall toggletemplate"><?php echo $block['template'] ?></a>
                        <br /><input type="text" value="<?php
                        echo $designFilePath . $block['template'];
                        ?>" size="40" onclick="this.select();" />
                                 <?php }; ?>
                </td>
                <td>
                    <?php echo $this->getRenderingTime($block) ?>
                </td>
            </tr>
            <?php $row++; ?>
        <?php endforeach ?>
    </tbody>
</table>

<h4><?php echo $this->__('Layout Blocks') ?></h4>
<p>List of all instantiated blocks, few of them might not be rendered.</p>
<table>
    <thead>
        <tr>
            <th>#</th>
            <th><?php echo $this->__('name in layout') ?></th>
            <th><?php echo $this->__('block class') ?></th>
            <th><?php echo $this->__('template') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $row = 0; ?>
        <?php foreach ($layoutBlocks as $block): ?>
            <tr class="<?php echo ( ($row % 2 ? 'djdebugodd' : 'djdebugeven')) ?>">
                <td><?php echo $row ?></td>
                <td><span style="color:grey;"><?php echo str_repeat("|&nbsp-&nbsp-&nbsp", $block['level']) ?></span><?php echo $block['layout_name'] ?></td>
                <td>
                    <a href="<?php echo $this->getViewBlockUrl($block['class']) ?>"
                       class="remoteCall"><?php echo $block['class'] ?></a>
                    <br /><input type="text" value="<?php
                    echo Mage::helper('debug')->getBlockFilename($block['class']);
                    ?>" size="40" onclick="this.select();" />
                </td>
                <td>
                    <?php if ($block['template']) {
                        ?>
                        <a href="<?php echo $this->getViewTemplateUrl($block['template']) ?>"
                           class="remoteCall toggletemplate"><?php echo $block['template'] ?></a>
                        <br /><input type="text" value="<?php
                        echo $designFilePath . $block['template'];
                        ?>" size="40" onclick="this.select();" />
                                 <?php }; ?>
                </td>
            </tr>
            <?php $row++; ?>
        <?php endforeach ?>
    </tbody>
</table>
